Default: &defaults
  database: illum.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: illum_test.sqlite3
  <<: *defaults

Staging:
  database: illum_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: illum_production.sqlite3
  poolsize: 100
  <<: *defaults
